#!/usr/bin/env bash
#Install nginx on your web server
#Nginx should be listening on port 80
#When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return Hello World!

#update and install nginx
sudo apt-get -y update 
sudo apt-get -y install nginx

#start nginx
sudo service start nginx

#allow firewall (traffix on port 80)
sudo ufw allow 'Nginx HTTP'

# Give the user ownership to website files for easy editing
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

# Backup default index
cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp

# Creating new index
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html

# Restarting nginx
sudo service nginx restart
